name: Moderation
description: "Moderation plugin for XMAS."
author: Azodox_
version: @version@
api-version: 1.18
main: fr.olten.moderation.Moderation
depend:
  - AccountSystem
commands:
  staffchat:
    description: "Send a message to the staff chat."
    usage: /staffchat <message>
    aliases:
      - sc
      - staff